name: lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    container: ghcr.io/aleksanderbobinski/workspace-bookmark-lint:develop
    steps:
      - uses: actions/checkout@v3
        with:
          path: ./workspace-bookmark
      - run: 'black --check --diff ./workspace-bookmark/src'
      - run: 'flake8 ./workspace-bookmark/src'
      - run: 'find ./workspace-bookmark/src -iregex .*py -print0 | xargs -n 1 -0 pylint'

