name: lint
on: [push]
jobs:
  build-lint-docker-image:
    uses: ./.github/workflows/docker-publish.yml
  lint:
    needs: [build-lint-docker-image]
    runs-on: ubuntu-latest
    container: ghcr.io/aleksanderbobinski/workspace-bookmark-lint:${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          path: ./workspace-bookmark
      - run: 'cd ./workspace-bookmark && scripts/lint.sh'
