name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/aleksanderbobinski/workspace-bookmark-test:develop
    steps:
      - uses: actions/checkout@v3
        with:
          path: ./workspace-bookmark
      - run: 'mkdir test'
      - run: bash -c 'cd test && python3 -m pytest ../workspace-bookmark/src/test_workspace_bookmark.py'
      - run: bash -c 'cd test && ../workspace-bookmark/src/test_g.bats'

