name: test
on: [push]
jobs:
  build-test-docker-image:
    uses: ./.github/workflows/docker-publish.yml
  test:
    needs: [build-test-docker-image]
    runs-on: ubuntu-latest
    container: ghcr.io/aleksanderbobinski/workspace-bookmark-test:${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3.6.0
        with:
          path: ./workspace-bookmark
      - run: 'cd ./workspace-bookmark && ./scripts/test.sh'
