name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/aleksanderbobinski/workspace-bookmark:develop
    steps:
      - uses: actions/checkout@v3
        with:
          path: ./workspace-bookmark
      - run: 'rm -Rf test && ./workspace-bookmark/src/create_test_dir.sh'
      - run: bash -c 'source ./workspace-bookmark/setup.sh && cd test && python3 -m pytest ../workspace-bookmark/src/test_workspace_bookmark.py'
      - run: bash -c 'source ./workspace-bookmark/setup.sh && cd test && ../workspace-bookmark/src/test_g.bats'

