name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/aleksanderbobinski/workspace-bookmark:develop
    steps:
      - uses: actions/checkout@v3
      - run: ./create_test_dir.sh
      - run: bash -c 'source setup.sh && python3 -m pytest ./test_workspace_bookmark.py'
      - run: bash -c 'source ./setup.sh && cd test && ../test_g.bats'

